# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    working_directory: ~/udacitiy-capstone
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch
        #working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            #Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            ls -la 
      - save_cache:
          paths:
            - ./venv
            - /bin/hadolint
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  lint:
    working_directory: ~/udacitiy-capstone
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch
        #working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            ls -la
            ls -la /bin/
            make lint 

workflows:
  default:
    jobs:
      - build
      - lint:
          requires: [build]