apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-capstone
  namespace: eks-capstone-ns
  labels:
    app: eks-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-capstone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eks-capstone
    spec:
      containers:
        - name: capstone
          image: 049928531231.dkr.ecr.eu-central-1.amazonaws.com/uda-repo:latest
          ports:
          - name: http
            containerPort: 80
          imagePullPolicy: Always